
# This is a template Makefile generated by rpcgen

# Parameters

CLIENT = tema1_client
SERVER = tema1_server

SOURCES_CLNT.c = 
SOURCES_CLNT.h = 
SOURCES_SVC.c = 
SOURCES_SVC.h = 
SOURCES.x = tema1.x

TARGETS_SVC.c = tema1_svc.c tema1_server.c tema1_xdr.c 
TARGETS_CLNT.c = tema1_clnt.c tema1_client.c tema1_xdr.c 
TARGETS = tema1.h tema1_xdr.c tema1_clnt.c tema1_svc.c tema1_client.c tema1_server.c

OBJECTS_CLNT = $(SOURCES_CLNT.c:%.c=%.o) $(TARGETS_CLNT.c:%.c=%.o)
OBJECTS_SVC = $(SOURCES_SVC.c:%.c=%.o) $(TARGETS_SVC.c:%.c=%.o)
# Compiler flags 

CFLAGS += -g -I/usr/include/tirpc
LDLIBS += -lnsl -ltirpc
RPCGENFLAGS = 

# Targets 

all : $(CLIENT) $(SERVER)

$(TARGETS) : $(SOURCES.x) 
	rpcgen $(RPCGENFLAGS) $(SOURCES.x)

$(OBJECTS_CLNT) : $(SOURCES_CLNT.c) $(SOURCES_CLNT.h) $(TARGETS_CLNT.c) 

$(OBJECTS_SVC) : $(SOURCES_SVC.c) $(SOURCES_SVC.h) $(TARGETS_SVC.c) 

$(CLIENT) : $(OBJECTS_CLNT) 
	$(LINK.c) -o $(CLIENT) $(OBJECTS_CLNT) $(LDLIBS) 

$(SERVER) : $(OBJECTS_SVC) 
	$(LINK.c) -o $(SERVER) $(OBJECTS_SVC) $(LDLIBS)

SERVER_ADDR=localhost
TESTNO=3
SERVER_PARAMS=tests/test$(TESTNO)/userIDs.db tests/test$(TESTNO)/resources.db tests/test$(TESTNO)/approvals.db
CLIENT_PARAMS=tests/test$(TESTNO)/client.in
TOKEN_LIFETIME=2

run_server: $(SERVER)
	./$(SERVER) $(SERVER_PARAMS) $(TOKEN_LIFETIME)

run_client: $(CLIENT)
	./$(CLIENT) $(SERVER_ADDR) $(CLIENT_PARAMS)

clean:
	$(RM) core $(OBJECTS_CLNT) $(OBJECTS_SVC) $(CLIENT) $(SERVER) *.out

