/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tema1.h"

bool_t
xdr_request_authorization_arg (XDR *xdrs, request_authorization_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->userid, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_authorization_status (XDR *xdrs, request_authorization_status *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_authorization_ret (XDR *xdrs, request_authorization_ret *objp)
{
	register int32_t *buf;

	 if (!xdr_request_authorization_status (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->auth_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_approve_request_token_arg (XDR *xdrs, approve_request_token_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->auth_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_approve_request_token_status (XDR *xdrs, approve_request_token_status *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_approve_request_token_ret (XDR *xdrs, approve_request_token_ret *objp)
{
	register int32_t *buf;

	 if (!xdr_approve_request_token_status (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_access_token_arg (XDR *xdrs, request_access_token_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->userid, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->auth_token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->automatically_refresh_token))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_access_token_status (XDR *xdrs, request_access_token_status *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_access_token_ret (XDR *xdrs, request_access_token_ret *objp)
{
	register int32_t *buf;

	 if (!xdr_request_access_token_status (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->renew_token, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->availability))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_refresh_access_token_arg (XDR *xdrs, refresh_access_token_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->userid, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->renew_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_refresh_access_token_status (XDR *xdrs, refresh_access_token_status *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_refresh_access_token_ret (XDR *xdrs, refresh_access_token_ret *objp)
{
	register int32_t *buf;

	 if (!xdr_refresh_access_token_status (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->renew_token, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->availability))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_delegated_action_arg (XDR *xdrs, validate_delegated_action_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->op_type, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->resource, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_delegated_action_status (XDR *xdrs, validate_delegated_action_status *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_delegated_action_ret (XDR *xdrs, validate_delegated_action_ret *objp)
{
	register int32_t *buf;

	 if (!xdr_validate_delegated_action_status (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}
