/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tema1.h"
#include <stdio.h> 
#include <time.h> 
#include <rpc/rpc.h> 

request_authorization_ret *
request_authorization_1_svc(request_authorization_arg *argp, struct svc_req *rqstp)
{
	static request_authorization_ret  result;

	/*
	 * insert server code here
	 */

	return &result;
}

request_access_token_ret *
request_access_token_1_svc(request_access_token_arg *argp, struct svc_req *rqstp)
{
	static request_access_token_ret  result;

	/*
	 * insert server code here
	 */

	return &result;
}

validate_delegated_action_ret *
validate_delegated_action_1_svc(validate_delegated_action_arg *argp, struct svc_req *rqstp)
{
	static validate_delegated_action_ret  result;

	/*
	 * insert server code here
	 */

	return &result;
}

approve_request_token_ret *
approve_request_token_1_svc(approve_request_token_arg *argp, struct svc_req *rqstp)
{
	static approve_request_token_ret  result;

	/*
	 * insert server code here
	 */

	return &result;
}
