/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tema1.h"
#include <stdio.h> 
#include <time.h> 
#include <rpc/rpc.h>
#include <string.h>

#define REQUEST "REQUEST"
#define INSERT	"INSERT"
#define MODIFY	"MODIFY"
#define READ	"READ"
#define EXECUTE	"EXECUTE"
#define DELETE	"DELETE"

CLIENT *clnt;
FILE *in_file;

void initialize_client(char *host, char *op_file) {
#ifndef	DEBUG
	clnt = clnt_create(host, TEMA1_PROG, TEMA1_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror("Eroare la crearea clientului");
		exit(1);
	}
#endif	/* DEBUG */

	in_file = fopen(op_file, "r");
	if (in_file == NULL) {
		printf("Eroare la deschiderea fisierului client.in\n");
		exit(1);
	}
}

void shutdown_client() {
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	fclose(in_file);
}

void run_client() {
	char *line = NULL;
	size_t len = 0;
	char *userID;
	char *action;
	char *resource;
	while (getline(&line, &len, in_file) != -1) {
		userID = strtok(line, ",");
		action = strtok(NULL, ",");
		resource = strtok(NULL, "\n");

		if (!strcmp(action, REQUEST)) {
			int refresh_token = atoi(resource);
			request_authorization_arg arg;
			arg.userID = userID;
			request_authorization_ret *result = request_authorization_1(&arg, clnt);
			char *auth_token = result->auth_token;
			char *access_token = NULL;
			// treat errors
			if (result == NULL) {
				clnt_perror(clnt, "Eroare la apelul RPC request_authorization_1");
				continue;
			}
			if (result->status == REQUEST_AUTHORIZATION_USER_NOT_FOUND) {
				printf("USER_NOT_FOUND\n");
				continue;
			}
			if (result->status == REQUEST_AUTHORIZATION_SUCCESS) {
				// next step is to sign the token
				approve_request_token_arg arg;
				arg.auth_token = auth_token;
				approve_request_token_ret *result = approve_request_token_1(&arg, clnt);
				// treat errors
				if (result == NULL) {
					clnt_perror(clnt, "Eroare la apelul RPC approve_request_token_1");
					continue;
				}
				if (result->status == APPROVE_REQUEST_TOKEN_SUCCESS) {
					// Next step is to request the access token
					request_access_token_arg arg;
					arg.userID = userID;
					arg.auth_token = auth_token;
					request_access_token_ret *result = request_access_token_1(&arg, clnt);
					// treat errors
					if (result == NULL) {
						clnt_perror(clnt, "Eroare la apelul RPC request_access_token_1");
						continue;
					}
					if (result->status == REQUEST_ACESS_TOKEN_REQUEST_DENIED) {
						printf("REQUEST_DENIED\n");
						continue;
					}
					if (result->status == REQUEST_ACESS_TOKEN_SUCCESS) {
						access_token = result->access_token;
						printf("%s -> %s\n", auth_token, access_token);
					}
				} else {
					printf("A avut loc o eroare necunoscuta: Approve Request Token\n");
				}
			} else {
				printf("A avut loc o eroare necunoscuta: Request Authorization\n");
			}
		}
	}
	
}

int
main (int argc, char *argv[])
{
	char *host;
	char *op_file;

	if (argc < 3) {
		printf ("Utilizare: %s <adresa_server> <fisier_operatii> \n", argv[0]);
		exit (1);
	}
	host = argv[1];
	op_file = argv[2];

	initialize_client(host, op_file);

	run_client();

	shutdown_client();

	return 0;
}
